language: cpp
sudo: required
dust: xenial
compiler:
- g++
os:
- linux
before_install:
- sudo apt-get update
- sudo apt-get install python-software-properties -y
- sudo apt-add-repository ppa:speth/cantera -y
- sudo apt-get update
- sudo apt-get install cantera-python cantera-python3 cantera-dev libgtkmm-3.0-dev gnuplot -y
- git clone https://github.com/eigenteam/eigen-git-mirror.git
branches:
  only:
  - master
env:
  global:
  - EIGEN=$PWD/eigen-git-mirror
  - CANTERA=/usr/
  - ASALI_OS='-DASALI_ON_WINDOW=0'
script:
  cd Ubuntu &
  g++ -std=c++11 -Wall -Wextra  $ASALI_OS -pthread src/main.cpp src/Asali.C src/BatchInterface.C src/BatchEquations.C src/Ph1DbvpInterface.C src/Ph1DodeInterface.C src/Ph1DEquations.C src/canteraInterface.C src/speciesPopup.C src/asaliKinetic.C src/asaliProperties.C src/runBar.C src/asaliPlot.C -Isrc/ -I$EIGEN -I$CANTERA/include -L$CANTERA/lib `pkg-config gtkmm-3.0 --cflags --libs` -Wl,--start-group -lcantera -lblas -llapack -lcantera_fortran -lsundials_ida -lsundials_cvode -lsundials_cvodes -lsundials_nvecserial -Wl,--end-group -lgfortran -Wl,--no-as-needed -ldl -lpthread -lm -o Asali
