
# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a GitHub project page then use these settings:
url: "http://srebughini.github.io/ASALI"
baseurl: "/ASALI"

# Of course don't forget to change the username and projectname to YOUR username and project
theme: jekyll-theme-minimal

# Name of website
title: ASALI: Modeling and beyond

# Short description of your site
description: A virtual proof that name is awesome!
